language: node_js
dist: trusty
sudo: required
node_js:
  - "7.6.0"

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

script:
  - npm install
#  - ng test --single-run
#  - ng test --cc --single-run
#  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
